# 공식문서에 나와 있는 Deployment 설정
## apps/v1 : /v1을 꼭 명시해야함.
apiVersion : apps/v1
kind: Deployment

metadata:
  name: spring-deployment
# Deployment 세부 정보
  ## backend-app 의 labels을 가진 pod를 배포
spec:
  replicas: 3
  selector:
    matchLabels:
      app: backend-app

  # 배포할 Pod 정의
  template:
    metadata:
      labels:
        app: backend-app
    spec:
      containers:
        - name:  spring-container
          image: spring-server:1.1
          imagePullPolicy : IfNotPresent
          ports:
            - containerPort : 8080
